### PR TITLE
fix caret cursor

### PR DESCRIPTION
**Pull request by tomlm**
#179 Caret is not being drawn by caret control.
For some reason the Line template wasn't being drawn. It never called into DrawingContext. I think it may be because we were drawing a line which had Width and Height but no start point or end point. I verified that Avalonia GUI ignores Lines with just width/height, so this is avalonia behavior.
I changed CaretControl template to output a Rectangle of width/1,height/1 and now it calls, gets rendered correctly.

### CODE REVIEW

**Comment by goe5mu** [comment]
Caret does not show up in ComboBoxItem. Visible when opening ComboBox.

**Comment by jinek** [comment]
Caret does not show up in ComboBoxItem. Visible when opening ComboBox.

**Comment by tomlm** [comment]
ComboBoxItem behavior is baked into Avalonia.
```csharp
   public ComboBoxItem()
   {
       this.GetObservable(ComboBoxItem.IsFocusedProperty)
           .Subscribe(focused =>
           {
               if (focused)
               {
                   (Parent as ComboBox)?.ItemFocused(this);
               }
           });
   }
```

**Comment by tomlm** [comment]
Hmmm....I can't seem to figure out how to get comboboxItem to show focus.

**Comment by tomlm** [comment]
I figured it out. I need to draw the movebrush AFTER the content is drawn, not before, otherwise the content resets the MoveBrush pixel

**Pull request merged**
