### PR TITLE
Add Italic, strikethrough and fix line draw bug 

### PR DESCRIPTION
**Pull request by tomlm**
* Added Italic support
* Turned on Strikethrough (although it renders as underline)
* Added Canvas gallery page
* Removed dependency on Crayon library

Bug Fixes
* Fix line draws 1 too many chars #132 

Changes:
* Remove dependency on Crayon library, as it didn't implement italics and added ConsoleUtils
* Use Italic escape to handle FontStyle=Italic
* Refactor DrawLineInternal into  DrawLineInternal and DrawRectangleLineInternal

Details:
The issue is that DrawLineInternal was written to draw rectangle borders and then simply reused as the DrawLine implementation. The original DrawLineInternal draws Corner + Line + Corner. This always ended up drawing 1 more than the desired line length, when reused for a simple line.

The solution was to refactor the code into
* DrawLineInternal
* DrawRectangleLineInternal

## Summary by CodeRabbit

- **New Features**
	- Introduced a new `GalleryCanvas` user control for enhanced graphical representation, including lines and rectangles.
	- Added text decoration demonstrations in `GalleryTextBlock`, showcasing underline, strikethrough, and italic styles.
	- New utility class `ConsoleUtils` for ANSI escape code definitions and text formatting.

- **Bug Fixes**
	- Improved text rendering logic in `InputLessDefaultNetConsole`, allowing for more flexible formatting.

- **Refactor**
	- Enhanced drawing functionality and error handling in `DrawingContextImpl`.
	- Updated strikethrough metrics in `GlyphTypeface`.

- **Chores**
	- Removed unused package reference for `Crayon`.
	- Removed metadata attributes from `GalleryColors`, `GalleryGradientBrush`, and `GalleryImage` classes.
	- Removed references to unused XAML and code files in the project configuration.

### CODE REVIEW

**Comment by jinek** [comment]
@tomlm don't you know why "code inspection" build did not work in this PR ?

**Comment by jinek** [comment]
@tomlm  Is this correct drawing? 
image

**Comment by tomlm** [comment]
There should be an orange box pinned to lower right corner....

**Comment by jinek** [comment]
> There should be an orange box pinned to lower right corner....

This one I've tried Fedora+Gnome Terminal

**Comment by tomlm** [comment]
Hmmm, I'll try on Ubuntu proper, I was using Ubuntu on wsl

**Comment by jinek** [comment]
> There should be an orange box pinned to lower right corner....
> 
> The upper left is testing horizontal and vertical one char lines
> 
> The bottom right is testing long lines that overlap
> 
> Lines look correct, but I don't know where the orange rect is

oh ok, it just did not fit:

Screenshot from 2024-11-02 00-13-44

**Comment by tomlm** [comment]
I was thinking about this more and I'm not certain I'm doing this right.

If I understand the current code, the goal is that lines actually meet at corners.

Effectively, startChar and endChars are lines that end at the middle of the pixel, so when you merge them the corners align.

So if I draw a line from pixel 0->pixel 1, what should it draw? It actually seems like it should draw a DOT at the corner. That seems weird.

But right now with my delta it does the following:
* DrawLineInternal => Draws from edge to edge.
* DrawRectangleLineInternal => Draws from center to center.
That's why my lines make overlapping cross where they pass. 

Thoughts?

**Comment by jinek** [comment]
I'm not sure I properly understand your concern.

> I was thinking about this more and I'm not certain I'm doing this right.
> 
> If I understand the current code, the goal is that lines actually meet at corners.
> 
> Effectively, startChar and endChars are lines that end at the middle of the pixel, so when you merge them the corners align.

Correct.

> So if I draw a line from pixel 0->pixel 1, what should it draw? It actually seems like it should draw a DOT at the corner. That seems weird.
> 
> But right now with my delta it does the following:
> 
>     * DrawLineInternal => Draws from edge to edge.
> 
>     * DrawRectangleLineInternal => Draws from center to center.
>       That's why my lines make overlapping cross where they pass.
> 
> 
> Thoughts?

Similar thoughts, but for now I can not fully understand how the line drawing is gonna be used. Will it be the line aligned to the text, like this?

```
────
The text.
```
Or will it be the line aligned to the rectangle, like this

```
╶─╴
┌─┐
│    │
└─┘

```

I would say we just need more input in the future on this question.

**Review by jinek — APPROVED** [review]

**Comment by tomlm** [comment]
I'm thinking we should extend line rush to have a policy for character layout

- Edge or center point
- perhaps alignment top/center/bottom assuming we can honor them with appropriate characters

Sometime like that...

**Pull request merged**
