### PR TITLE
105 choredeps upgrade avalonia dependencies to 1100

### PR DESCRIPTION
**Pull request by jinek**
image

### CODE REVIEW

**Comment by tomlm** [comment]
It's not clear what the expected state of things are, but here is my results from testing the gallery app on Windows and Ubuntu.

# Windows
* **Calendar** 
  * select range throws exception with DoubleClick|MouseMoved combo event
  * select multi-range throws exception with DoubleClick|MouseMoved combo event
* **Calendar Picker**
  * layout wonky
* **ComboBox** 
  * layout wonky
* **Listbox**
  * Layout wonky
  * can't scroll?
* **TextBlock**
  * Layout wonky
* **Data grid**
  * layout wonky
* **Scrollviewer**
  * doesn't scroll
  
# Ubuntu
* **Calendar** 
  * select range doesn't seem to work
  * select multi-range doesn't seem to work.
* **ScrollViewer**
  * horizontal scroll doesn't seem to work

**Comment by tomlm** [comment]
It would be good to have a drag and drop test in the gallery, as I think the events for click and move are not modeled correctly.

**Comment by jinek** [comment]
> It would be good to have a drag and drop test in the gallery, as I think the events for click and move are not modeled correctly.

True.
But, I think this should be addressed in a separate task. In this PR, it is probably better just to upgrade to new Avalonia while avoiding regression. I'm assuming existing issues from the previous version nay remain.

**Review by tomlm — APPROVED** [review]
I"m going to approve despite not really understanding the code, because it's important to get onto the avalonia 11 code base :)

**Comment by tomlm** [comment]
Hey, I have 2 bug fixes to this delta. Do you want me to just push to this PR are do a separate PR? 
Fixed
* click drag causes exception to throw
* Scroll wheel takes 12 clicks to scroll listbox 1 notch.
* Added Cursor viewer to gallery so you can inspect cursor events.
Cursor

**Comment by tomlm** [comment]
Wow, ok. I was testing the wrong branch. I just tested with the avalonia based code 11 and it works MUCH better!

Nice job!
(BTW: my bug fixes still apply)

**Comment by jinek** [comment]
> Hey, I have 2 bug fixes to this delta. Do you want me to just push to this PR or do a separate PR? 
> Fixed
> * click drag causes exception to throw
> * Scroll wheel takes 12 clicks to scroll listbox 1 notch.
> * Added Cursor viewer to gallery so you can inspect cursor events.
> Cursor
> 
>  

Great! I think better to do a separate one.

**Review by tomlm — APPROVED** [review]

**Comment by jinek** [comment]
> Nice job! (BTW: my bug fixes still apply)

Thank you for help very much! We can now jump to your fixes/improvements.

**Pull request merged**
